# Generated by Django 5.0.4 on 2024-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("sku", models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
